######################## default configuration ####################
baseURL = "https://shorttech2026.github.io"
languageCode = "zh-tw"
title = "Short Tech 2026"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "Blog"
URL = "blog/"
weight = 1

[[menu.main]]
name = "About Me"
URL = "about/"
weight = 2

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Sunwc's Blog"
# Meta data
description = "Meta data"
author = "sunwc"
# Google Analitycs
googleAnalitycsID = "Your ID"

# copyright
copyright = "| copyright &copy; 2021 [Themefisher](https://themefisher.com/hugo-themes/) All Rights Reserved |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "github"
icon = "ti-github"                     # themify icon : https://themify.me/themify-icons
link = "https://github.com/ching89118"

[[params.social]]
title = "dotblogs"
icon = "ti-notepad"                                 # themify icon : https://themify.me/themify-icons
link = "https://dotblogs.com.tw/lucy_NoteForCoding"

[markup]
[markup.highlight]
style = 'xcode-dark'

[markup.goldmark.parser]
attribute = true
